@echo off
echo Switching to PAID mode (Anthropic / Claude)...
copy /Y "%USERPROFILE%\.claude\settings.paid.json" "%USERPROFILE%\.claude\settings.json" >nul
echo Done. Launching Claude...
claude --dangerously-skip-permissions
